#!/usr/bin/env python3
"""Strict differential baseline check, with limited modal replay; NOT a safety verifier."""
import argparse
import hashlib
import json
import math
from pathlib import Path
import re

STAMP = re.compile(r'^; generated by OrcaSlicer 2\.4\.2 on \d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2}$')
WORD = re.compile(r'([XYZEF])([+-]?(?:\d+(?:\.\d*)?|\.\d+))')
OPAQUE = {'SET_VELOCITY_LIMIT', 'M73', 'M106', 'M140'}


def normalized(data):
    # Only the observed timestamp changes; version, warnings, comments and ALL
    # commands remain significant. No tolerances on XYZ/E/F/order.
    return '\n'.join('; generated by OrcaSlicer 2.4.2 [timestamp]' if STAMP.fullmatch(line) else line
                     for line in data.split('\n'))


def replay(data):
    xyz = [None, None, None]
    feed = None
    absolute_xyz = relative_e = False
    units_mm = False
    moves = []
    for line in data.splitlines():
        code = line.split(';', 1)[0].strip()
        if not code:
            continue
        parts = code.split(maxsplit=1)
        op = parts[0]
        if op in OPAQUE:
            continue  # compared byte-for-byte, not physically interpreted
        if op == 'G90':
            absolute_xyz = True
        elif op == 'M83':
            relative_e = True
        elif op == 'G21':
            units_mm = True
        elif op in ('G0', 'G1'):
            if not (absolute_xyz and relative_e and units_mm):
                raise ValueError('unsupported/uninitialized motion mode')
            text = parts[1] if len(parts) > 1 else ''
            fields = WORD.findall(text)
            if WORD.sub('', text).strip() or len(dict(fields)) != len(fields):
                raise ValueError('unsupported or repeated motion word')
            values = {k: float(v) for k, v in fields}
            if not all(math.isfinite(v) for v in values.values()):
                raise ValueError('nonfinite motion')
            start = tuple(xyz)
            for i, axis in enumerate('XYZ'):
                if axis in values:
                    xyz[i] = values[axis]
            feed = values.get('F', feed)
            moves.append((start, tuple(xyz), values.get('E', 0), feed))
        else:
            raise ValueError('unsupported replay command: ' + op)
    if not moves:
        raise ValueError('empty motion stream')
    return moves


def same_settings(reference, candidate, allow_nptop_off_default=False):
    if reference == candidate:
        return True
    # B01 adds one namespaced default in the resolved-config schema. Keep all
    # other bytes significant; this exception never touches commands or goldens.
    line = b'\t"nptop_mode": "off",\n'
    return (allow_nptop_off_default and b'"nptop_mode"' not in reference and
            candidate.count(line) == 1 and candidate.replace(line, b'', 1) == reference)


def compare(reference, candidate, allow_nptop_off_default=False):
    reference_manifest = json.loads((reference / 'manifest.json').read_text())
    candidate_manifest = json.loads((candidate / 'manifest.json').read_text())
    expected = {(m, mode) for m in ('flat_block', 'wedge_5deg', 'shallow_sphere') for mode in ('off', 'zaa')}
    for manifest in (reference_manifest, candidate_manifest):
        if len(manifest['runs']) != 6 or {(r['model'], r['mode']) for r in manifest['runs']} != expected:
            raise ValueError('all three distinct fixtures in both modes are required')
    rows = []
    for run, new_run in zip(reference_manifest['runs'], candidate_manifest['runs']):
        if (run['model'], run['mode'], run['input_sha256']) != (new_run['model'], new_run['mode'], new_run['input_sha256']):
            raise ValueError('different baseline inputs')
        if run['exit_code'] != 0 or new_run['exit_code'] != 0:
            raise ValueError('failed baseline run')
        # Rehash actual artifacts, including final G-code, settings and run logs.
        for base, manifest_run in ((reference, run), (candidate, new_run)):
            for file, digest in manifest_run['files'].items():
                if hashlib.sha256((base / file).read_bytes()).hexdigest() != digest:
                    raise ValueError('artifact changed: ' + file)
        name = run['model'] + '-' + run['mode']
        a = (reference / name / 'output/plate_1.gcode').read_text()
        b = (candidate / name / 'output/plate_1.gcode').read_text()
        if normalized(a) != normalized(b):
            raise ValueError('G-code difference beyond timestamp: ' + name)
        old_settings = (reference / name / 'resolved.json').read_bytes()
        new_settings = (candidate / name / 'resolved.json').read_bytes()
        if not same_settings(old_settings, new_settings, allow_nptop_off_default):
            raise ValueError('resolved settings changed: ' + name)
        moves = replay(a)
        if moves != replay(b):
            raise ValueError('modal replay differs: ' + name)
        sloped = sum(start[2] is not None and start[2] != end[2] and e > 0 and
                     start[:2] != end[:2] for start, end, e, feed in moves)
        if run['mode'] == 'zaa' and run['model'] != 'flat_block' and not sloped:
            raise ValueError('ZAA baseline contains no sloped extrusions')
        rows.append({'fixture': name, 'motion_commands': len(moves), 'sloped_extrusions': sloped,
                     'resolved_settings': 'IDENTICAL' if old_settings == new_settings else 'ADDED_NPTOP_OFF_DEFAULT_ONLY',
                     'differential': 'PASS', 'safety_verification': 'NOT_RUN'})
    return rows


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('reference', type=Path)
    parser.add_argument('candidate', type=Path)
    parser.add_argument('--allow-nptop-off-default', action='store_true',
                        help='Permit only the exact B01 namespaced OFF default line in resolved.json')
    args = parser.parse_args()
    try:
        print(json.dumps(compare(args.reference, args.candidate, args.allow_nptop_off_default), indent=2))
    except (ValueError, OSError, KeyError) as error:
        parser.exit(2, str(error) + '\n')
