import unittest
from compare_baselines import normalized, replay, same_settings


class BaselineTests(unittest.TestCase):
    sample = 'G90\nG21\nM83\nG1 X10 Y20 Z3 F600\nG1 X12 Z3.2 E.4\nG1 E-.8\nG1 E.8\n'

    def test_B01_only_explicit_additive_off_default_is_allowed(self):
        before = b'{\n\t"flow": 1\n}\n'
        after = b'{\n\t"nptop_mode": "off",\n\t"flow": 1\n}\n'
        self.assertTrue(same_settings(before, before))
        self.assertFalse(same_settings(before, after))
        self.assertTrue(same_settings(before, after, True))
        for changed in [after.replace(b'off', b'safe_hybrid'), after.replace(b'off', b'future_mode'),
                        after.replace(b'1', b'2'), after.replace(b'"flow"', b'"new_motion_setting"'),
                        after.replace(b'{', b'{\n\t"extra": 0,'), after.replace(b'\t"flow"', b' "flow"')]:
            self.assertFalse(same_settings(before, changed, True))
        self.assertFalse(same_settings(after, before, True))

    def test_ORC02_ORC03_modal_replay_preserves_xyz_e_feed_order(self):
        moves = replay(self.sample)
        self.assertEqual(moves[1], ((10, 20, 3), (12, 20, 3.2), .4, 600))
        self.assertEqual([m[2] for m in moves], [0, .4, -.8, .8])

    def test_ORC02_normalization_only_removes_timestamp(self):
        a = '; generated by OrcaSlicer 2.4.2 on 2026-09-27 at 12:00:00\n' + self.sample
        self.assertEqual(normalized(a), normalized(a.replace('12:00:00', '13:00:00')))
        for before, after in [('X12', 'X13'), ('E.4', 'E4'), ('F600', 'F6000'), ('2.4.2', '2.4.3')]:
            self.assertNotEqual(normalized(a), normalized(a.replace(before, after)))
        self.assertNotEqual(normalized(a), normalized(a + '; warning: modified\n'))

    def test_ORC03_mutations_change_replay(self):
        expected = replay(self.sample)
        for before, after in [('X12', 'X13'), ('E.4', 'E4'), ('F600', 'F6000')]:
            self.assertNotEqual(expected, replay(self.sample.replace(before, after)))

    def test_unsupported_or_empty_replay_rejects(self):
        for text in ['', 'G1 X2', self.sample + 'PRINT_START\n', self.sample.replace('M83', 'M82'),
                     self.sample + 'G1 X1 X2\n', self.sample + 'G1 XNaN\n']:
            with self.assertRaises(ValueError):
                replay(text)


if __name__ == '__main__':
    unittest.main()
