cmake_minimum_required(VERSION 3.13)
foreach(key NPTOP_SOURCE_ROOT NPTOP_OUTPUT NPTOP_CONFIGURATIONS)
    if(NOT DEFINED ${key})
        message(FATAL_ERROR "Missing ${key}")
    endif()
endforeach()
function(json_string value result)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    foreach(code RANGE 1 31)
        string(ASCII ${code} character)
        if(value MATCHES "${character}")
            message(FATAL_ERROR "Unsupported control character in build input")
        endif()
    endforeach()
    set(${result} "\"${value}\"" PARENT_SCOPE)
endfunction()
function(write_if_changed path bytes)
    if(EXISTS "${path}")
        file(READ "${path}" previous)
        if(previous STREQUAL bytes)
            return()
        endif()
    endif()
    file(WRITE "${path}.tmp" "${bytes}")
    file(RENAME "${path}.tmp" "${path}")
endfunction()
function(artifact_realpath path result)
    # REALPATH alone leaves a missing leaf unresolved on older CMake/macOS.
    # Resolve the nearest existing ancestor, retaining the missing suffix.
    set(suffix "")
    while(NOT EXISTS "${path}")
        get_filename_component(name "${path}" NAME)
        get_filename_component(parent "${path}" DIRECTORY)
        if(parent STREQUAL path OR name STREQUAL "")
            message(FATAL_ERROR "Cannot resolve inventory consumer path")
        endif()
        set(suffix "/${name}${suffix}")
        set(path "${parent}")
    endwhile()
    get_filename_component(physical "${path}" REALPATH)
    set(${result} "${physical}${suffix}" PARENT_SCOPE)
endfunction()
file(STRINGS "${NPTOP_OUTPUT}/files.txt" inputs ENCODING UTF-8)
if(NOT inputs)
    message(FATAL_ERROR "Empty build input inventory")
endif()
list(LENGTH inputs count)
if(count GREATER 100000)
    message(FATAL_ERROR "Build input file limit")
endif()
set(sorted "${inputs}")
list(REMOVE_DUPLICATES sorted)
list(SORT sorted)
if(NOT sorted STREQUAL inputs)
    message(FATAL_ERROR "Unsorted or duplicate build input inventory")
endif()
set(rows "")
set(separator "")
foreach(path ${inputs})
    if(path MATCHES "(^|/)\\.\\.(/|$)|^[\\/]|[;\n\r]" OR IS_DIRECTORY "${NPTOP_SOURCE_ROOT}/${path}")
        message(FATAL_ERROR "Invalid build input path: ${path}")
    endif()
    file(SHA256 "${NPTOP_SOURCE_ROOT}/${path}" digest)
    string(SHA256 key "${path}")
    set(hash_${key} "${digest}")
    json_string("${path}" encoded)
    string(APPEND rows "${separator}[${encoded},\"${digest}\"]")
    set(separator ",")
endforeach()
string(REPLACE "|" ";" configurations "${NPTOP_CONFIGURATIONS}")
foreach(config ${configurations})
    set(config_path "${config}")
    if(config STREQUAL "NoConfig")
        set(config_path "")
    endif()
    include("${NPTOP_OUTPUT}/${config_path}/context.cmake")
    set(inventory_artifacts "")
    if(EXISTS "${NPTOP_OUTPUT}/${config_path}/artifacts.cmake")
        include("${NPTOP_OUTPUT}/${config_path}/artifacts.cmake")
    endif()
    set(build "{")
    set(separator "")
    foreach(key CMAKE_CXX_COMPILER_ID CMAKE_CXX_COMPILER_VERSION CMAKE_CXX_FLAGS
            CMAKE_GENERATOR CMAKE_SYSTEM_NAME CMAKE_SYSTEM_PROCESSOR CMAKE_VERSION
            configuration flags_${config} inventory_options target_definitions target_options)
        # Configuration-specific flags use a stable field name in the schema.
        set(name "${key}")
        if(key STREQUAL "flags_${config}")
            set(name "configuration_flags")
        endif()
        json_string("${name}" encoded_key)
        json_string("${${key}}" encoded_value)
        string(APPEND build "${separator}${encoded_key}:${encoded_value}")
        set(separator ",")
    endforeach()
    string(APPEND build "}")
    set(json "{\"build\":${build},\"files\":[${rows}],\"schema\":1,\"scope\":\"build-input-inventory\"}")
    string(LENGTH "${json}" json_length)
    string(LENGTH "${build}" build_length)
    if(json_length GREATER 16777216 OR build_length GREATER 6000)
        message(FATAL_ERROR "Build input byte limit")
    endif()
    # Separate literals keep each below MSVC's limit; split only at file rows,
    # never inside a UTF-8 path. No timestamps, absolute source paths or env capture.
    string(SHA256 digest "${json}")
    string(SUBSTRING "${digest}" 0 12 delimiter)
    if(json MATCHES "\\)${delimiter}\"")
        message(FATAL_ERROR "Build inventory raw-string delimiter collision")
    endif()
    set(header "#pragma once\nnamespace Slic3r::nptop::detail {\ninline constexpr const char *build_input_parts[] = {\n")
    set(part "{\"build\":${build},\"files\":[")
    set(separator "")
    foreach(path ${inputs})
        # Use already hashed bytes, not a second filesystem observation.
        json_string("${path}" encoded)
        string(SHA256 key "${path}")
        set(row "${separator}[${encoded},\"${hash_${key}}\"]")
        string(LENGTH "${part}${row}" length)
        if(length GREATER 8000)
            string(APPEND header "R\"${delimiter}(${part})${delimiter}\",\n")
            set(part "")
        endif()
        string(APPEND part "${row}")
        set(separator ",")
    endforeach()
    set(footer "],\"schema\":1,\"scope\":\"build-input-inventory\"}")
    string(LENGTH "${part}${footer}" length)
    if(length GREATER 8000)
        string(APPEND header "R\"${delimiter}(${part})${delimiter}\",\n")
        set(part "")
    endif()
    string(APPEND part "${footer}")
    string(APPEND header "R\"${delimiter}(${part})${delimiter}\"\n};\ninline constexpr const char *build_inputs_sha256 = \"${digest}\";\n}\n")
    set(header_path "${NPTOP_OUTPUT}/${config_path}/NonplanarBuildInputsData.hpp")
    set(previous "")
    if(EXISTS "${header_path}")
        file(READ "${header_path}" previous)
    endif()
    if(NOT previous STREQUAL header)
        # These exact paths come from CMake's TARGET_OBJECTS, not guessed object
        # naming or caller resource bytes. Missing consumer means recompile and
        # relink even if the changed header shares a coarse mtime with the object.
        if(CMAKE_GENERATOR MATCHES "Makefiles")
            get_filename_component(build_root "${inventory_build_root}" REALPATH)
            foreach(artifact ${inventory_objects} ${inventory_artifacts})
                artifact_realpath("${artifact}" physical)
                string(FIND "${physical}" "${build_root}/" prefix)
                if(NOT prefix EQUAL 0)
                    message(FATAL_ERROR "Inventory consumer outside the build tree: ${artifact}")
                endif()
            endforeach()
            file(REMOVE ${inventory_objects} ${inventory_artifacts})
        endif()
    endif()
    write_if_changed("${NPTOP_OUTPUT}/${config_path}/inventory.json" "${json}")
    write_if_changed("${header_path}" "${header}")
endforeach()
